name: ubuntu
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Generate timestamp for weekly cache invalidation
        id: current-time
        run: echo "formattedTime=$(date +%Y-%V)" >> $GITHUB_OUTPUT
      - name: Setup TeX Live
        uses: ./
        with:
          version: 2022
          cache-key: texlive-ubuntu-latest-${{ steps.current-time.outputs.formattedTime }}
          packages-path: ${{ github.workspace }}/.github/texlive.packages
          profile-path: ${{ github.workspace }}/.github/texlive.profile
      - name: Test tlmgr availability
        run: tlmgr version
      - name: Test run for latex
        run: latex small2e
      - name: Test run from pdflatex
        run: pdflatex sample2e
