name: windows-most-recent
on:
  push:
  schedule:
    - cron: "0 0 1/10 * *"
jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Generate timestamp for monthly cache invalidation
        id: current-time
        run: Write-Output "formattedTime=$(Get-Date -UFormat %Y-%m)" >> $Env:GITHUB_OUTPUT
      - name: Setup TeX Live
        uses: ./
        with:
          # leave `repository` unset to get the latest
          cache-key: texlive-windows-latest-${{ steps.current-time.outputs.formattedTime }}
          packages-path: ${{ github.workspace }}/.github/texlive.packages
          profile-path: ${{ github.workspace }}/.github/texlive.profile
      - name: Test tlmgr availability
        run: tlmgr version
      - name: Test run for latex
        run: latex small2e
      - name: Test run from pdflatex
        run: pdflatex sample2e
